site_name: D4CG Documentation
nav:
  - Privacy Notice: 'PcdcPrivacyNotice.md'
  - GEARBOx Terms and Conditions: 'GEARBOxTermsandConditions.md'
  - 'PCDC Documentation':
    - Acceptable Use Policy: 'AcceptableUsePolicy.md'
    - Statistical Manual: 'StatisticalManual.md'
    - User Guide: 'DataPortalUserGuide.md'
    - Data Access and Governance: 'DataAccessAndGovernance.md'
    - Project Request Forms: 'PCDCProjectRequestForm.md'
    - Terms and Conditions: 'TermsAndConditions.md'
    - Software Updates: 'SoftwareUpdates.md'
    - Data Release Updates: 'DataReleases.md'
    - Working with PFB Files: 'WorkingWithPFBfiles.md'
  - 'Data Modeling and Reporting':
    - Overview: 'DataModelingOverview.md'
    - Longitudinal Reporting: 'LongitudinalReporting.md'
    - Genomic Reporting: 'GenomicReporting.md'
    - Tumor Reporting:  'TumorReporting.md'
  - 'Data Commons Video Tutorials':
    - Introduction to the PCDC <br>: 'https://youtu.be/uSUFthO4aBs'
    - Cohort Explorer Overview: 'https://youtu.be/0TJJpx3m0GY'
    - Filter Sets and Survival Analysis: 'https://youtu.be/oosUz_M8gfs'
    - Statistical Considerations: 'https://youtu.be/d_x8taJ-lP8'

theme:
  name: material
  font:
    text: Raleway
  favicon: img/favicon.ico
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

    # prev_next_buttons_location: none
    # include_homepage_in_sidebar: False
#    logo: img/PcdcLogo.png
