# This is a basic workflow to help you get started with Actions

name: Email Notification For Acceptable Use Policy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - 'AcceptableUsePolicy.md'
    branches:
      - main
  pull_request:
    paths:
      - 'AcceptableUsePolicy.md'
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-secret:
      runs-on: ubuntu-latest
      outputs:
        my-key: ${{ steps.my-key.outputs.defined }}
      steps:
          - id: my-key
            if: "${{ env.MY_KEY != 'None' }}"
            run: echo "::set-output name=defined::true"
            env:
                MY_KEY: ${{ secrets.EMAILLIST }}
  job1:
      runs-on: ubuntu-latest
      needs: [check-secret]
      if: needs.check-secret.outputs.my-key == 'true'
      steps:
        - uses: actions/checkout@v3
        - name: Send Email Action
          uses: cinotify/github-action@v1.1.0
          with:
            to: ${{ secrets.EMAILLIST }}
            subject: 'Document Commit'
            body: 'Document(s) in ${{github.repository}} called AcceptableUsePolicy.md was comitted'

  job2:
      runs-on: ubuntu-latest
      needs: [check-secret]
      if: needs.check-secret.outputs.my-key != 'true'
      steps:
        - uses: actions/checkout@v3
        - name: Send Email Action
          uses: cinotify/github-action@v1.1.0
          with:
            to: 'lgraglia@bsd.uchicago.edu'
            subject: 'Document Commit'
            body: 'Document(s) in ${{github.repository}} called AcceptableUsePolicy.md was comitted'
  Trigger_API_ActUsePol:
      env:
        type: "portal-acceptable-use-policy"
        version: 1
        name: "Data Portal Acceptable Use Policy"
        raw: "https://github.com/chicagopcdc/chicagopcdc.github.io/blob/main/docs/AcceptableUsePolicy.md"
        formatted: "https://docs.pedscommons.org/AcceptableUsePolicy/"
        required: true
        API_KEY: ${{ secrets.APIKEY }}
        KEY_ID: ${{ secrets.KEYID }}
        REQUESTURL: ${{ secrets.REQUESTURL }}
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@3
      - name: Run a Python script
        run: python .github/workflows/key.py
      - name: Trigger API
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ env.TOKEN }}" -d '{ "type": "'"$type"'", "version": "'"$version"'", "name": "'"$name"'", "raw": "'"$raw"'", "formatted": "'"$formatted"'", "required": true }' http://localhost/user/admin/add_document
  
  
